### PR TITLE
Update Meteosat URLs

### PR DESCRIPTION
**Pull request by erget**
We're migrating our image library, as described here:
http://oiswww.eumetsat.org/facilities/html/imagegallery.php

More cool updates are to come, including a more navigable API.
I don't have the libraries installed on this box to test this, but I think it should work.

Do you have a test harness you can throw this into to make sure it's all OK?

### CODE REVIEW

**Comment by domoritz** [comment]
Thank you for the patch! My test harness is me trying going through a list of manual tests. I'll do that today (hello from Berlin).

**Comment by domoritz** [comment]
Btw, it would be awesome to have an actual API for the latest image date instead of me having to scrape the HTML pages. Is that coming as well? I saw that https://www.eumetsat.int/website/home/News/DAT_4335631.html?lang=EN&pState=1 says that "Enhanced API" is planned.

**Comment by domoritz** [comment]
Thank you for the fix. Worked perfectly. I also switched to the enhanced images since the look much nicer. 🚀

**Comment by domoritz** [comment]
Requests are working again (https://meteosat-url.appspot.com/msg). I need to set up some kind of alerting if error rates are high.

**Comment by erget** [comment]
Happy to do it - I know that an API is planned and I'm hoping it's just a WMS, but I'm not sure how it'll be developed. I suggest it'll be a part of our new data services that are under construction at the moment ;)

**Comment by domoritz** [comment]
Sweet. Looking forward to it. I also enabled email notifications for errors in appengine so next time I will know right away when something fails.

**Pull request merged**
